CREATE TRIGGER dbo.DV_TriggerUpdate
   ON  [dbo].[DOCVEN_PWRAPP]
   AFTER UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
		
	BEGIN TRY
		UPDATE [dbo].[FACT_DETALLE]
			SET ID_FACT = i.ID,
				NUMERO_FACTURA = i.NUMERO_FACTURA,
				FECHA_EMISION = i.FECHA_EMISION,
				MONTO = i.MONTO, 
				MONEDA = i.MONEDA, 
				NOMBRE_CLIENTE = i.NOMBRE_CLIENTE,
				CONDICION_PAGO = i.CONDICION_PAGO,
				VENDEDOR = i.VENDEDOR,
				CANCELADO = i.CANCELADO,
				ESTADO = i.ESTADO,
				COBRADO = i.COBRADO,
				SALDO = i.SALDO,
				NC_FACTURA_CANJE = i.NC_FACTURA_CANJE,
				NC_ANULACION = i.NC_ANULACION,
				TITULO_GRATUITO = i.TITULO_GRATUITO,
				EMPRESA = i.EMPRESA,
				DIRECCION_ENTREGA = i.DIRECCION_ENTREGA,
				SEDE = i.SEDE,
				ID_APP = i.ID_APP,
				OC_CLIENTE = i.OC_CLIENTE,
				TIPO_CLIENTE = i.TIPO_CLIENTE,
				USUARIO_REGISTRO = i.USUARIO_REGISTRO
			FROM inserted AS i
			WHERE ID_FACT = i.ID
	END TRY
	BEGIN CATCH
		DECLARE @MensajeError NVARCHAR(4000);
		DECLARE @SeveridadError INT;
		DECLARE @EstadoError INT;

		SELECT @MensajeError = ERROR_MESSAGE(), @SeveridadError = ERROR_SEVERITY(), @EstadoError = ERROR_STATE()

		RAISERROR(@MensajeError,@SeveridadError,@EstadoError)
		ROLLBACK TRANSACTION
	END CATCH

END
GO