CREATE TRIGGER dbo.DV_TriggerInsert 
   ON  [dbo].[DOCVEN_PWRAPP]
   AFTER INSERT
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
		
	BEGIN TRY
		BEGIN
			INSERT INTO dbo.FACT_BUSQUEDA (NUMERO_FACTURA, ID_APP, FECHA_EMISION, OC_CLIENTE)
			SELECT i.NUMERO_FACTURA, i.ID_APP, i.FECHA_EMISION, i.OC_CLIENTE
			FROM inserted  AS i
			ORDER BY i.FECHA_EMISION
		END
		BEGIN
			INSERT INTO dbo.FACT_DETALLE (
				ID_FACT,
				NUMERO_FACTURA,
				FECHA_EMISION,
				MONTO, 
				MONEDA, 
				NOMBRE_CLIENTE,
				CONDICION_PAGO,
				VENDEDOR,
				CANCELADO,
				ESTADO,
				COBRADO,
				SALDO,
				NC_FACTURA_CANJE,
				NC_ANULACION,
				TITULO_GRATUITO,
				EMPRESA,
				DIRECCION_ENTREGA,
				SEDE,
				ID_APP,
				OC_CLIENTE,
				TIPO_CLIENTE,
				USUARIO_REGISTRO
			)
			SELECT i.ID, i.NUMERO_FACTURA, i.FECHA_EMISION, i.MONTO, i.MONEDA, 
				i.NOMBRE_CLIENTE, i.CONDICION_PAGO, i.VENDEDOR, i.CANCELADO,
				i.ESTADO, i.COBRADO, i.SALDO, i.NC_FACTURA_CANJE, i.NC_ANULACION,
				i.TITULO_GRATUITO, i.EMPRESA, i.DIRECCION_ENTREGA, i.SEDE, i.ID_APP, 
				i.OC_CLIENTE, i.TIPO_CLIENTE, i.USUARIO_REGISTRO
			FROM inserted  AS i
			ORDER BY i.FECHA_EMISION
		END
	END TRY
	BEGIN CATCH
		DECLARE @MensajeError NVARCHAR(4000);
		DECLARE @SeveridadError INT;
		DECLARE @EstadoError INT;

		SELECT @MensajeError = ERROR_MESSAGE(), @SeveridadError = ERROR_SEVERITY(), @EstadoError = ERROR_STATE()

		RAISERROR(@MensajeError,@SeveridadError,@EstadoError)
		ROLLBACK TRANSACTION
	END CATCH

END
GO