--DELETE FROM [dbo].[PEND_ITEMS]
--DBCC CHECKIDENT('PEND_ITEMS', RESEED, 0)
SELECT * FROM [dbo].[auth_user] --user client123

SELECT * FROM SURGICORP_POWERAPPS.[dbo].[GUIPEN_PWRAPP] WHERE CANTIDAD > 0 --725 213  --
SELECT * FROM SURGICORP_POWERAPPS.[dbo].[PEND_GUIAS] WHERE NUMERO_GUIA='T001-9281'	--1 518
--SELECT DISTINCT(NUMERO_GUIA), EMPRESA FROM SURGICORP_POWERAPPS.[dbo].[GUIPEN_PWRAPP] WHERE CANTIDAD > 0 --1 518
SELECT * FROM SURGICORP_POWERAPPS.[dbo].[PEND_ITEMS] /*WHERE NUMERO_GUIA='T001-9281'*/ ORDER BY NUMERO_GUIA DESC	--9 229
--SELECT * FROM SURGICORP_POWERAPPS.[dbo].[GUIPEN_PWRAPP] WHERE CANTIDAD > 0	--9 229
SELECT  * FROM SURGICORP_POWERAPPS.[dbo].[PEND_UPDATE_AUDIT] ORDER BY id DESC
SELECT  * FROM [dbo].[MEDICO_PWRAPP]
SELECT  * FROM [dbo].[MEDICOS]
SELECT  * FROM [dbo].[ID_PWRAPP]