SELECT * FROM [dbo].[USR_STRMVI] 
WHERE STRMVI_SUCURS + '-' + CAST(STRMVI_NROFOR AS varchar(20)) = 'T001-48173' --or STRMVI_DEPOSI = 'SGTSA1' T005-21284
ORDER BY STRMVI_NROFOR desc

-- Descripcion de Guias
SELECT TOP 5000 * FROM [dbo].[GR_DESCRIPCION] 
WHERE NUMERO_GUIA = 'T001-39339'
--WHERE PRODUCTO = 'C7636'
ORDER BY id desc

-- Consultas al QR_PRODUCTOS
SELECT * FROM [dbo].[QR_PRODUCTOS]
WHERE LOTE = '5181884S.'
--WHERE CODIGO_QR <> '' 
ORDER BY id desc
SELECT * FROM [dbo].[QR_UPDATE_AUDIT] ORDER BY id desc
-- Consultas al codigo QR
SELECT * FROM [dbo].[USR_STMLOH] WHERE STMLOH_CODBAR is null or STMLOH_CODBAR = ''
-- Consultas a GR_AUDIT
SELECT TOP 5000 * FROM [dbo].[GR_UPDATE_AUDIT] 
ORDER BY id desc
--CREATE INDEX GR_descr_empr ON [dbo].[GR_DESCRIPCION] (EMPRESA_ID);
--DELETE FROM [GR_DESCRIPCION]
--DBCC CHECKIDENT('GR_DESCRIPCION', RESEED, 0)
/*UPDATE [GR_DESCRIPCION]
SET PROVEEDOR = i.STRMVI_NOMPPR, DESCRIPCION_PRODUCTO_HP = i.STMPDH_DESART
FROM (SELECT (ROW_NUMBER() OVER( PARTITION BY STRMVI_SUCURS + '-' + CAST(STRMVI_NROFOR AS varchar(20)) ORDER BY STRMVI_CODFOR, STRMVI_NROFOR, STRMVI_NROITM, STRMVI_NIVEXP ASC)) as nro_item, * 
	FROM [dbo].[USR_STRMVI]) 
	as i
WHERE [GR_DESCRIPCION].ID_CONCAT = i.STRMVI_CODEMP  + ' | ' + i.STRMVI_MODFOR + ' | ' + i.STRMVI_CODFOR +  ' | ' + i.STRMVI_SECTOR + ' | ' + i.STRMVI_NSERIE + 
	' | ' + i.STRMVI_SUCURS + ' | ' + CAST(i.STRMVI_NROFOR AS varchar(20)) + ' | ' + i.STRMVI_ARTORI + ' | ' + CAST(i.STRMVI_NROSEC AS varchar(20)) --and [GR_DESCRIPCION].id > 243799*/

/*UPDATE GR_DESCRIPCION
SET CANTIDAD = 1 --, NUMERO_SECUENCIA = 1 --, ID_CONCAT = '01 | ST | SGRG3 | AN-E.1 | N/A | T003 | 29289 | BJ1005 | 1' 
WHERE id = 402751*/

--INSERT INTO dbo.GR_DESCRIPCION
--	(
--		ID_CONCAT,
--		NUMERO_ITEM,
--		NUMERO_SECUENCIA,
--		PRODUCTO,
--		DESCRIPCION_PRODUCTO,
--		DESCRIPCION_PRODUCTO_HP,
--		PROVEEDOR,
--		SECTOR,
--		NUMERO_GUIA,
--		CANTIDAD,
--		LOTE,
--		VENCIMIENTO_LOTE,
--		EMPRESA_ID,
--		UBICACION_SECTOR,
--		KITS_GUIA,
--		KITS_ITEM,
--		TIPO_PRODUCTO,
--		USUARIO
--	)
--SELECT i.STRMVI_CODEMP  + ' | ' + i.STRMVI_MODFOR + ' | ' + i.STRMVI_CODFOR +  ' | ' + i.STRMVI_SECTOR + ' | ' + i.STRMVI_NSERIE + 
--	' | ' + i.STRMVI_SUCURS + ' | ' + CAST(i.STRMVI_NROFOR AS varchar(20)) + ' | ' + i.STRMVI_ARTORI + ' | ' + CAST(i.STRMVI_NROSEC AS varchar(20)),
--	i.STRMVI_NROITM, i.STRMVI_NROSEC, i.STRMVI_ARTORI, i.STMPDH_DESCRP, i.STMPDH_DESART, i.STRMVI_NOMPPR, i.STRMVI_SECTOR, 
--	i.STRMVI_SUCURS + '-' + CAST(i.STRMVI_NROFOR AS varchar(20)), IIF(i.STRMVI_CANTID < 0, i.STRMVI_CANTID * (-1), i.STRMVI_CANTID), 
--	i.STRMVI_NSERIE, i.USR_STMLOH_FCHVEN, i.STRMVI_CODEMP, ISNULL(i.USR_UBFSEC_DESCRP, 'Sin Ubicación'), i.KITS_GUIA, i.KITS_ITEM, i.STRMVI_TIPPRO,
--	'Creado por Servidor'
--FROM [USR_STRMVI] AS i
--WHERE i.STRMVI_SUCURS + '-' + CAST(i.STRMVI_NROFOR AS varchar(20)) = 'T001-34746' and
--	i.STRMVI_CODEMP = '01'