--BACKUP LOG SURGICORP_ERP TO DISK = 'NUL' WITH NOFORMAT, NOINIT, SKIP, NOREWIND, NOUNLOAD, STATS = 10;
DBCC SQLPERF(LOGSPACE);
exec sp_helptext '[dbo].[INSERT_IDPAPP]'

-- Consultas a ID_APP tabla para OFISIS
SELECT * FROM USR_IDPAPP
ORDER BY IDPAPP_NROAPP desc

--INSERT INTO USR_IDPAPP (IDPAPP_NROAPP, IDPAPP_FCHREG, IDPAPP_VNDDOR)
--	VALUES (30579, '2026-05-25T15:57:38', '');   

--DELETE FROM USR_IDPAPP WHERE IDPAPP_NROAPP = 30584
-- 5a36f8c8-06eb-f011-8406-7ced8da8d46c  Sara Magaly Chuchon Garamendi

--UPDATE USR_IDPAPP
--	SET IDPAPP_VNDDOR = 'Sara Magaly Chuchon Garamendi'
--WHERE IDPAPP_NROAPP = 30582