SELECT NUMERO_FACTURA, ID_APP, OC_CLIENTE, FECHA_EMISION FROM SURGICORP_POWERAPPS.dbo.DOCVEN_PWRAPP ORDER BY FECHA_EMISION
--WHERE NUMERO_FACTURA='F003-20544'   23281
SELECT TOP 1500 * FROM [dbo].[DOCVEN_PWRAPP]
ORDER BY FECHA_EMISION DESC 
SELECT TOP 1500 * FROM [dbo].[FACT_DETALLE] ORDER BY RV desc
SELECT TOP 1500 * FROM [dbo].[FACT_UPDATE_AUDIT] ORDER BY id desc
--WHERE NUMERO_FACTURA = 'F003-26764'
SELECT TOP 1500 * FROM [dbo].[FACT_DETALLE]
ORDER BY id desc
/*UPDATE [dbo].[FACT_DETALLE]
SET SEDE = '-'
WHERE SEDE is null]*/
--WHERE NUMERO_FACTURA='F001-6226'
--INSERT INTO dbo.FACT_BUSQUEDA(NUMERO_FACTURA, ID_APP, FECHA_EMISION, OC_CLIENTE)
--SELECT i.NUMERO_FACTURA, i.ID_APP, i.FECHA_EMISION, i.OC_CLIENTE
--FROM dbo.DOCVEN_PWRAPP  AS i
--ORDER BY i.FECHA_EMISION
--DELETE FROM [dbo].[PEND_ITEMS]
--DBCC CHECKIDENT('PEND_ITEMS', RESEED, 0)
SELECT * FROM [dbo].[auth_user] --user client123
