SELECT * FROM [dbo].[USR_STRMVI] 
WHERE STRMVI_SECTOR = 'R2.4' --or STRMVI_DEPOSI = 'SGTSA1' 
ORDER BY STRMVI_NROFOR desc
SELECT * FROM [dbo].[USR_STMLOH] WHERE STMLOH_CODBAR is null or STMLOH_CODBAR = ''
SELECT TOP 5000 * FROM [dbo].[GR_UPDATE_AUDIT] 
ORDER BY id desc
SELECT TOP 5000 * FROM [dbo].[GR_DESCRIPCION] 
--WHERE NUMERO_GUIA = 'T003-32929' 
WHERE PRODUCTO = 'C7636'
ORDER BY id desc
SELECT * FROM [dbo].[QR_PRODUCTOS]
WHERE LOTE = '5181884S.'
--WHERE CODIGO_QR <> '' 
ORDER BY id desc
SELECT * FROM [dbo].[QR_UPDATE_AUDIT] ORDER BY id desc
--CREATE INDEX GR_descr_empr ON [dbo].[GR_DESCRIPCION] (EMPRESA_ID);
--DELETE FROM [GR_DESCRIPCION]
--DBCC CHECKIDENT('GR_DESCRIPCION', RESEED, 0)
/*UPDATE [GR_DESCRIPCION]
SET PROVEEDOR = i.STRMVI_NOMPPR, DESCRIPCION_PRODUCTO_HP = i.STMPDH_DESART
FROM (SELECT (ROW_NUMBER() OVER( PARTITION BY STRMVI_SUCURS + '-' + CAST(STRMVI_NROFOR AS varchar(20)) ORDER BY STRMVI_CODFOR, STRMVI_NROFOR, STRMVI_NROITM, STRMVI_NIVEXP ASC)) as nro_item, * 
	FROM [dbo].[USR_STRMVI]) 
	as i
WHERE [GR_DESCRIPCION].ID_CONCAT = i.STRMVI_CODEMP  + ' | ' + i.STRMVI_MODFOR + ' | ' + i.STRMVI_CODFOR +  ' | ' + i.STRMVI_SECTOR + ' | ' + i.STRMVI_NSERIE + 
	' | ' + i.STRMVI_SUCURS + ' | ' + CAST(i.STRMVI_NROFOR AS varchar(20)) + ' | ' + i.STRMVI_ARTORI + ' | ' + CAST(i.STRMVI_NROSEC AS varchar(20)) --and [GR_DESCRIPCION].id > 243799*/

/*UPDATE GR_DESCRIPCION
SET CANTIDAD = 1 --, NUMERO_SECUENCIA = 1 --, ID_CONCAT = '01 | ST | SGRG3 | AN-E.1 | N/A | T003 | 29289 | BJ1005 | 1' 
WHERE id = 402751*/

