SELECT FCRMVH_NROGUI, FCRMVH_DESDPT, FCRMVH_DEPTRA, FCRMVH_DEPOSI, FCRMVH_SECTOR, USR_FCTTMT_DESCRIP, FCRMVH_FECALT FROM [dbo].[USR_FCRMVH] 
SELECT TOP 6000 * FROM [dbo].[USR_FCRMVH] 
WHERE FCRMVH_NROFOR = '46938'
--WHERE USR_FCTTMT_DESCRIP like '%UBICACION TRANSITORIA%'
ORDER BY FCRMVH_FECALT desc
SELECT * FROM [dbo].[USR_SALGUI]
SELECT * FROM [dbo].[USR_ANUGUI]
SELECT * FROM [dbo].GR_BUSQUEDA
SELECT * FROM [dbo].[FEEDBACK]
SELECT* FROM [dbo].[auth_user]
SELECT * FROM [dbo].[extended_users]
SELECT * FROM [dbo].[django_admin_log]
SELECT* FROM [dbo].[django_session]
SELECT * FROM [dbo].[USR_VALCON]
SELECT * FROM [dbo].[USR_VTRMVH]
SELECT * FROM sys.messages 
WHERE severity >= 16 and language_id = 3082
ORDER BY message_id desc
SELECT TOP 2000 * FROM [dbo].GUIAS_REMISION 
--WHERE NUMERO_GUIA = 'T001-46938'
ORDER BY id desc
SELECT * FROM [dbo].HOJA_PICKING 
WHERE NUMERO_GUIA = 'T001-46910'
--WHERE APP_SESSION_ACTIVE is not null
ORDER BY id desc
SELECT * FROM [dbo].[HP_UPDATE_AUDIT] 
--WHERE NUMERO_GUIA = 'T003-850' --t001-46938
ORDER BY id desc
SELECT TOP 80000 * FROM [dbo].[GR_UPDATE_AUDIT]
--WHERE NUMERO_GUIA = 'T001-46938'
ORDER BY id desc
SELECT * FROM [dbo].[SI_Empresa]
SELECT * FROM [sys].[traces]
--INSERT INTO [dbo].[SI_Empresa](EMPRESA) VALUES('RR MEDICAL S.R.L.')
--DELETE FROM [GR_UPDATE_AUDIT] WHERE id > 463229
--DBCC CHECKIDENT('GR_UPDATE_AUDIT', RESEED, 463230)
SELECT NUMERO_GUIA, COUNT(NUMERO_GUIA) AS cantidad 
FROM GUIAS_REMISION 
GROUP BY NUMERO_GUIA
--CREATE INDEX HP_nroGuia ON [dbo].[HOJA_PICKING] (NUMERO_GUIA);
/*UPDATE dbo.HOJA_PICKING
	SET GR_ID = i.id
	FROM GUIAS_REMISION AS i
	WHERE HOJA_PICKING.NUMERO_GUIA = i.NUMERO_GUIA AND
		HOJA_PICKING.EMPRESA_ID = i.EMPRESA_ID*/
/*UPDATE dbo.HOJA_PICKING
	SET STATUS_PICKING = 'Picking Pendiente'
	WHERE id = 25174 -- and STATUS_PICKING = 'Picking Terminado'*/
/*UPDATE GUIAS_REMISION
SET FECHA_CIRUGIA = TRY_PARSE(CONCAT(CONVERT(date, USR_FCRMVH_FCHCIR), 
		' ', 
		STUFF(COALESCE(NULLIF(USR_FCRMVH_HORCIR, ''), '1200'), 3, 0, ':'), 
		' ', 
		IIF(USR_FCRMVH_TIPHOR = 'P', 'PM', 'AM')
	) as datetime using 'en-us'
)
FROM [USR_FCRMVH] as i
WHERE NUMERO_GUIA = i.FCRMVH_NROGUI and EMPRESA_ID = i.FCRMVH_CODEMP*/
/*UPDATE GUIAS_REMISION
	SET CODIGO_TRANSFERENCIA = i.FCRMVH_DEPTRA,
		TRANSFERENCIA = i.FCRMVH_DESDPT
FROM [USR_FCRMVH] as i
WHERE NUMERO_GUIA = i.FCRMVH_NROGUI and EMPRESA_ID = i.FCRMVH_CODEMP*/