SELECT  * FROM [dbo].[GR_DESCRIPCION]
WHERE NUMERO_GUIA='T001-7451' --and
--where (OC_CLIENTE='') --and 450130 448954
ORDER BY id desc
--FECHA_GUIA >= DATEADD(DAY,-1,CURRENT_TIMESTAMP)
--FECHA_GUIA >= Cast(CURRENT_TIMESTAMP as date)
--DELETE FROM GR_BUSQUEDA
--DBCC CHECKIDENT('GR_BUSQUEDA', RESEED, 0)
SELECT TOP 1500 * FROM [dbo].[GR_BUSQUEDA]
--WHERE NUMERO_GUIA='T001-7451'  
ORDER BY id DESC 
--SELECT TOP 1500 * FROM [dbo].[GUIAS_REMISION] ORDER BY id DESC 
--SELECT TOP 2500 * FROM [dbo].[GUIAS_REMISION_OC] ORDER BY id DESC
--SELECT TOP 2000 * FROM [dbo].[GR_DESCRIPCION] WHERE NUMERO_GUIA='T005-9407' ORDER BY NUMERO_GUIA DESC
--SELECT TOP 2000 * FROM [dbo].[GR_DESCRIPCION_OC] ORDER BY id DESC
--SELECT * FROM [dbo].[DOCGUI_PWRAPP] WHERE /*(OC_CLIENTE='' or OC_CLIENTE  is null) and*/ NUMERO_GUIA='T005-9407' ORDER BY FECHA_GUIA DESC
--SELECT TOP 1500 * FROM [dbo].GR_BUSQUEDA /* WHERE NUMERO_GUIA='T001-7140'*/ ORDER BY id DESC 
--DELETE FROM [HOJA_PICKING]
--DBCC CHECKIDENT('HOJA_PICKING', RESEED, 0)
SELECT TOP 1500 * FROM [dbo].[HOJA_PICKING]
--WHERE NUMERO_GUIA = 'T001-7288'
ORDER BY id desc
SELECT TOP 1000 id,NUMERO_GUIA,OC_CLIENTE,LIMA_PROVINCIA FROM [dbo].[HOJA_PICKING]
--WHERE LIMA_PROVINCIA = 2 
ORDER BY id desc
--sp_get_distributor
--SELECT TOP 1000 * FROM [dbo].[DOCGUI_PWRAPP] WHERE NUMERO_GUIA='T003-18145'

/*UPDATE GR_DESCRIPCION
SET UBICACION_SECTOR = i.UBICACION_SECTOR
FROM DOCGUI_PWRAPP As i*/