SELECT * FROM [dbo].[SI_KITS_prod_id]
SELECT * FROM [dbo].[SI_KITS]
SELECT * FROM [dbo].[SI_TIPOPRODUCTO]
SELECT * FROM [dbo].[USR_PARINT]
SELECT * FROM [dbo].[USR_VTTVND]
SELECT * FROM [dbo].[USR_VTTENT]
SELECT * FROM [dbo].[USR_VTMCLH]

-- Consulta a Stock de Transito
SELECT * FROM [dbo].[USR_OCEPEN]
WHERE OCEPEN_ARTCOD = '8135025S'

-- envíos de ID_APP a OFISIS 8135025S
SELECT * FROM [dbo].[USR_IDPAPP]
--INSERT INTO [USR_IDPAPP] (IDPAPP_NROAPP, IDPAPP_FCHREG, IDPAPP_VNDDOR)
--VALUES(29857, GETDATE(), 'Sabina Ojeda Guerrero');

-- consulta a la tabla audits
SELECT TOP 80 * FROM [dbo].[SI_UPDATE_AUDIT]
WHERE TABLA = 'PRODUCTOS' and
	CAMPO = 'UPDATED'
ORDER BY id desc

-- consulta a sector
SELECT * FROM [dbo].[USR_STTDEI] 
WHERE STTDEI_SECTOR = 'PRI-R153.B'
SELECT * FROM [dbo].[SI_SECTOR]

-- consulta a Depositos
SELECT * FROM [dbo].[USR_STTDEH]
SELECT * FROM [dbo].[SI_DEPOSITO] 
WHERE CODIGO_DEPOSITO = 'SG-C215-C'

-- consultas a tipo de almacen
SELECT * FROM [dbo].[SI_TIPOALMACEN]

-- Consultas a descripcion de stock
SELECT * FROM [dbo].[SI_DESCRIPCION]
WHERE GUIA_REMISION is not NULL

-- Consultas a la tabla de stock_inventario  --35 654
SELECT * FROM [dbo].[STOCK_INVENTARIO] as i
	LEFT JOIN SI_PRODUCTO as p ON p.id = i.PRODUCTO_ID
WHERE PRODUCTO_ID = 11931
--WHERE USUARIO like '%Servidor%'
ORDER BY USUARIO desc

--Consultas a la tabla stock de ofisis
SELECT /*TOP 22000*/ STRMVK_SECTOR, STRMVK_DEPOSI, STRMVK_DESDEP, STRMVK_TIPAMJ, STRMVK_TIPPRO, STRMVK_ARTCOD, STRMVK_NSERIE, STRMVK_CANTID, * FROM [dbo].[USR_STRMVK]
--WHERE STRMVK_DEPOSI like '%-CUA'
WHERE STRMVK_ARTCOD = '1116681'
	and STRMVK_NSERIE = '0303665622'
	and STRMVK_TIPAMJ = 'VTA. SUJET. A CONF(MER)/BIENES DE USO' 
ORDER BY STRMVK_FECALT desc


-- Consultas a tabla Productos ofisis
SELECT * FROM [dbo].[USR_STMPDH]
--WHERE STMPDH_LINEAD = 'EQUIPOS MÉDICOS' and STMPDH_NOMPRO like 'HUMECA%'
WHERE STMPDH_ARTCOD = '1748'
ORDER BY STMPDH_FECALT desc

-- Consultas a Categoría de Productos
SELECT CODIGO_PRODUCTO, si_producto_id, sa_categoria_id, NOMBRE_CATEGORIA FROM [dbo].[SI_PRODUCTO_cat_id]
LEFT JOIN [SI_PRODUCTO] as p ON si_producto_id = p.id
LEFT JOIN SA_CATEGORIA as c ON sa_categoria_id = c.id

--INSERT INTO [SI_PRODUCTO_cat_id] (si_producto_id, sa_categoria_id)
--SELECT i.id, 227 FROM (SELECT * FROM SI_PRODUCTO WHERE CODIGO_PRODUCTO like 'TP1T%' and TIPO like 'MER%') as i

-- Consultas a Productos
SELECT * FROM [dbo].[SI_PRODUCTO]
--LEFT JOIN SI_LINEA as l ON l.id = LINEA_ID
--LEFT JOIN SI_PROVEEDOR as p ON p.id = PROVEEDOR_ID  
WHERE CODIGO_PRODUCTO like 'EBA-55%'
--WHERE l.NOMBRE_LINEA = 'EQUIPOS MÉDICOS' and p.NOMBRE_PROVEEDOR like 'HUMECA%'

-- Consultas a grupo
SELECT * FROM [dbo].[USR_GRUNEG]
SELECT * FROM [dbo].[SI_GRUPO] 
--WHERE NOMBRE_GRUPO = 'LAMPARA'
ORDER BY NOMBRE_GRUPO

-- Consultas a linea
SELECT * FROM [dbo].[USR_LINNEG]
--WHERE LINNEG_DESCRP like '%GENERAL'
ORDER BY LINNEG_DESCRP
SELECT * FROM [dbo].[SI_LINEA] 
WHERE NOMBRE_LINEA like '%GENERAL'
ORDER BY NOMBRE_LINEA

-- Consultas a proveedor
SELECT * FROM [dbo].[USR_PVMPRH]
WHERE PVMPRH_NOMBRE = 'MINDMAZE SA'
ORDER BY PVMPRH_NOMBRE
SELECT * FROM [dbo].[SI_PROVEEDOR]
--WHERE NOMBRE_LINEA = 'LAMPARA'
ORDER BY NOMBRE_PROVEEDOR

--consultas a las familias de los productos
SELECT * FROM [dbo].[USR_FAMALT]
SELECT * FROM [dbo].[SI_FAMILIA]

--consultas a las familias de los productos aprobados
SELECT * FROM [dbo].[SA_FAMILIA]

--consultas a la categoría de los productos aprobados
SELECT * FROM [dbo].[SA_CATEGORIA]
--UPDATE [SA_CATEGORIA]
--SET TIPO_ID = 19
--WHERE id >= 195 and id <= 198
--DELETE [SA_CATEGORIA] WHERE id > 102 
--DBCC CHECKIDENT('SA_CATEGORIA', RESEED, 102)

-- consulta a Stock Aprobados
SELECT s.id, PRODUCTO_ID, p.CODIGO_PRODUCTO, DISPONIBLE, IMPORTACION, INKJET, ACONDICIONADO, REESTERILIZADO, OBSERVADOS, CONSIGNACION, VENTA_SUJETA, STOCK, USUARIO 
FROM [dbo].[STOCK_APROBADO] as s
LEFT JOIN SI_PRODUCTO As p ON p.id = PRODUCTO_ID
WHERE p.CODIGO_PRODUCTO = '1116681'
--WHERE USUARIO is not null

SELECT STRMVK_NSERIE, STRMVK_TIPPRO, STRMVK_ARTCOD,  STRMVK_TIPAMJ, STRMVK_TIPALM, SUM(STRMVK_CANTID) FROM [dbo].[USR_STRMVK]
WHERE STRMVK_ARTCOD = '1116681'

--DELETE FROM [STOCK_APROBADO] WHERE id < 2678116 GUIA_DIGEMID --5104  5750 1922 7026       5794 4047
--DBCC CHECKIDENT('STOCK_APROBADO', RESEED, 0)
--INSERT INTO SI_PRODUCTO (CODIGO_PRODUCTO, DESCRIPCION)
--DELETE FROM [SI_DESCRIPCION]
--DBCC CHECKIDENT('SI_DESCRIPCION', RESEED, 0)
--CREATE INDEX SI_CodProd ON [dbo].[SI_PRODUCTO] (CODIGO_PRODUCTO);    -- 208594 + 31 = 208596?

--UPDATE [dbo].[SI_DESCRIPCION]
--	SET DEPOSITO_ID = NULL,
--		SECTOR_ID = NULL

--INSERT INTO SI_DESCRIPCION (CODIGO_PRODUCTO, CANTIDAD, DESCRIPCION_ID, LOTE, TIPOALMACEN_ID, DEPOSITO_ID, SECTOR_ID, TIPO_ALMACENAJE)
SELECT t.cod, t.stock, t.st_id, t.STRMVK_NSERIE, t.tp_id, t.d_id, t.s_id, t.STRMVK_TIPAMJ
	FROM (SELECT DISTINCT TOP 480000 STRMVK_ARTCOD as cod, p.id as p_id, SUM(STRMVK_CANTID) as stock, i.STRMVK_NSERIE, d.id as d_id, i.STRMVK_DEPOSI, s.id as s_id, i.STRMVK_SECTOR, i.STRMVK_DESSEC, tp.id as tp_id, i.STRMVK_TIPALM, st.id as st_id, i.STRMVK_TIPAMJ/*, dc.id*/ FROM [USR_STRMVK] as i
		LEFT JOIN SI_PRODUCTO as p ON p.CODIGO_PRODUCTO = i.STRMVK_ARTCOD and p.TIPO = i.STRMVK_TIPPRO
		LEFT JOIN SI_DEPOSITO as d ON d.CODIGO_DEPOSITO = i.STRMVK_DEPOSI
		LEFT JOIN SI_SECTOR as s ON s.NOMBRE_SECTOR = i.STRMVK_SECTOR and s.CODIGO_DEPOSITO = i.STRMVK_DEPOSI
		LEFT JOIN SI_TIPOALMACEN as tp ON tp.NOMBRE_ALMACEN = i.STRMVK_TIPALM
		LEFT JOIN STOCK_INVENTARIO as st ON st.PRODUCTO_ID = p.id
	--	LEFT JOIN SI_DESCRIPCION as dc ON dc.DESCRIPCION_ID = st.id and 
	--			dc.LOTE = i.STRMVK_NSERIE and
	--			dc.TIPOALMACEN_ID = tp.id and
	--			dc.DEPOSITO_ID = d.id and
	--			dc.SECTOR_ID = s.id and
	--			dc.TIPO_ALMACENAJE = i.STRMVK_TIPAMJ
	--WHERE dc.id is NULL
	GROUP BY STRMVK_ARTCOD, p.id, STRMVK_NSERIE, d.id, STRMVK_DEPOSI, s.id, STRMVK_SECTOR, tp.id, STRMVK_TIPALM, st.id, i.STRMVK_TIPAMJ, i.STRMVK_DESSEC--, dc.id
	ORDER BY STRMVK_ARTCOD desc) as t

--DBCC OPENTRAN(SURGICORP)

-- Insert a Stock de Inventario
--INSERT INTO STOCK_INVENTARIO (PRODUCTO_ID, ALMACENAJE, STOCK, TIPO_ALMACENAJE)
SELECT st.p_id, st.almcenaje, st.stock, st.tipo_almacenaje FROM (
	SELECT TOP 60000 p.id as p_id, STRMVK_ARTCOD as cod, p.TIPO as tipo, IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ) as tipo_almacenaje,
		(e.EMPRESA + ' | ' + IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ) + ' | ' + i.STRMVK_TIPALM) As almcenaje, SUM(STRMVK_CANTID) as stock 
	FROM [USR_STRMVK] as i
		LEFT JOIN [SI_PRODUCTO] as p ON p.CODIGO_PRODUCTO = i.STRMVK_ARTCOD and TIPO = i.STRMVK_TIPPRO
		LEFT JOIN [dbo].[SI_Empresa] As e ON e.id = i.STRMVK_CODEMP
	GROUP BY p.id, STRMVK_ARTCOD, p.TIPO, IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ), (e.EMPRESA + ' | ' + IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ) + ' | ' + i.STRMVK_TIPALM) 
	ORDER BY STRMVK_ARTCOD, p_id desc
) as st
--WHERE tipo_almacenaje is null
ORDER BY st.p_id asc

--DELETE FROM [STOCK_INVENTARIO]
--DBCC CHECKIDENT('STOCK_INVENTARIO', RESEED, 0)

BEGIN
	MERGE STOCK_APROBADO AS target
	USING (
		SELECT TOP 60000 p.id as p_id, i.STRMVK_ARTCOD as cod,
			SUM(CASE WHEN (STRMVK_TIPAMJ = 'STOCK DISPONIBLE' 
				or STRMVK_TIPAMJ = 'CONSUMO INTERNO'
				or STRMVK_TIPAMJ = 'DEVOLUCION EN PROCESO'
				or STRMVK_TIPAMJ = 'STOCK EN TRANSITO')
				and (STRMVK_SECTOR <> '7-B.1'
				and STRMVK_SECTOR <> '7-B.2'
				and STRMVK_SECTOR <> '7-B.3'
				and STRMVK_SECTOR <> 'PRI-C1.G.1'
				and STRMVK_SECTOR <> 'PRI-R116.A'
				and STRMVK_SECTOR <> 'PRI-R116.B'
				and STRMVK_SECTOR <> 'PRI-R116.C'
				and STRMVK_SECTOR <> 'PRI-R116.D'
				and STRMVK_SECTOR <> 'PRI-R116.E'
				and STRMVK_SECTOR <> 'PRI-R88.C'
				and STRMVK_SECTOR <> 'PRI-R75.A.1')
				THEN i.STRMVK_CANTID ELSE 0 END) as disponible,
			SUM(CASE WHEN STRMVK_SECTOR = 'PRI-C1.G.1'
				and STRMVK_SECTOR = 'PRI-R116.A'
				and STRMVK_SECTOR = 'PRI-R116.B'
				and STRMVK_SECTOR = 'PRI-R116.C'
				and STRMVK_SECTOR = 'PRI-R116.D'
				and STRMVK_SECTOR = 'PRI-R116.E'
				and STRMVK_SECTOR = 'PRI-R88.C'
				THEN i.STRMVK_CANTID ELSE 0 END) as reservado,
			SUM(CASE WHEN (STRMVK_TIPAMJ = 'PRODUCTOS OBSERVADOS POR CALIDAD'
				or STRMVK_TIPAMJ = 'IMPORTACION EN PROCESO DE APROBACION'
				or STRMVK_TIPAMJ = 'COMPRA LOCAL EN PROCESO DE REVISION')
				and (STRMVK_SECTOR <> '7-B.1'
				and STRMVK_SECTOR <> '7-B.2'
				and STRMVK_SECTOR <> '7-B.3'
				and STRMVK_SECTOR <> 'PRI-R75.A.1')
				THEN i.STRMVK_CANTID ELSE 0 END) as importacion,
			SUM(CASE WHEN STRMVK_TIPAMJ = 'INKJET' 
				and (STRMVK_SECTOR <> '7-B.1'
				and STRMVK_SECTOR <> '7-B.2'
				and STRMVK_SECTOR <> '7-B.3'
				and STRMVK_SECTOR <> 'PRI-R75.A.1')
				THEN i.STRMVK_CANTID ELSE 0 END) as inkjet,
			SUM(CASE WHEN STRMVK_TIPAMJ = 'PRODUCTOS EN ACONDICIONADO' 
				and (STRMVK_SECTOR <> '7-B.1'
				and STRMVK_SECTOR <> '7-B.2'
				and STRMVK_SECTOR <> '7-B.3'
				and STRMVK_SECTOR <> 'PRI-R75.A.1')
				THEN i.STRMVK_CANTID ELSE 0 END) as acondicionado,
			SUM(CASE WHEN STRMVK_TIPAMJ = 'PRODUCTO REESTERILIZADO' 
				and (STRMVK_SECTOR <> '7-B.1'
				and STRMVK_SECTOR <> '7-B.2'
				and STRMVK_SECTOR <> '7-B.3'
				and STRMVK_SECTOR <> 'PRI-R75.A.1')
				THEN i.STRMVK_CANTID ELSE 0 END) as reesterilizado,
			SUM(CASE WHEN STRMVK_SECTOR = '7-B.1' 
				or STRMVK_SECTOR = '7-B.2'
				or STRMVK_SECTOR = '7-B.3'
				or STRMVK_SECTOR = 'PRI-R75.A.1'
				THEN i.STRMVK_CANTID ELSE 0 END) as observados,
			SUM(CASE WHEN STRMVK_TIPAMJ = 'VTA. SUJET. A CONF(MER)/BIENES DE USO' 
				and (STRMVK_SECTOR <> '7-B.1'
				and STRMVK_SECTOR <> '7-B.2'
				and STRMVK_SECTOR <> '7-B.3'
				and STRMVK_SECTOR <> 'PRI-R75.A.1')
				THEN i.STRMVK_CANTID ELSE 0 END) as venta_sujeta,
			SUM(CASE WHEN STRMVK_TIPAMJ = 'CONSIGNACION' 
				and (STRMVK_SECTOR <> '7-B.1'
				and STRMVK_SECTOR <> '7-B.2'
				and STRMVK_SECTOR <> '7-B.3'
				and STRMVK_SECTOR <> 'PRI-R75.A.1')
				THEN i.STRMVK_CANTID ELSE 0 END) as consignacion,
			SUM(CASE WHEN STRMVK_TIPAMJ = 'STOCK DISPONIBLE' 
				or STRMVK_TIPAMJ = 'CONSUMO INTERNO'
				or STRMVK_TIPAMJ = 'DEVOLUCION EN PROCESO'
				or STRMVK_TIPAMJ = 'STOCK EN TRANSITO'
				or STRMVK_TIPAMJ = 'PRODUCTOS OBSERVADOS POR CALIDAD'
				or STRMVK_TIPAMJ = 'IMPORTACION EN PROCESO DE APROBACION'
				or STRMVK_TIPAMJ = 'COMPRA LOCAL EN PROCESO DE REVISION'
				or STRMVK_TIPAMJ = 'INKJET'
				or STRMVK_TIPAMJ = 'PRODUCTOS EN ACONDICIONADO'
				or STRMVK_TIPAMJ = 'PRODUCTO REESTERILIZADO'
				or STRMVK_TIPAMJ = 'VTA. SUJET. A CONF(MER)/BIENES DE USO'
				or STRMVK_TIPAMJ = 'CONSIGNACION' 
				THEN i.STRMVK_CANTID ELSE 0 END) as stock
		FROM [USR_STRMVK] as i
			LEFT JOIN [dbo].[SI_Empresa] As e ON e.id = i.STRMVK_CODEMP
			OUTER APPLY (
				SELECT TOP 1 *
				FROM [SI_PRODUCTO] as p
				WHERE p.CODIGO_PRODUCTO = i.STRMVK_ARTCOD
					and TIPO = i.STRMVK_TIPPRO
				ORDER BY p.ID -- Aquí decides cuál de las dos cuentas priorizar	IMPORTACION EN PROCESO DE APROBACION
			) as p
		GROUP BY STRMVK_ARTCOD, p.id
		ORDER BY STRMVK_ARTCOD asc
	) AS source
	ON (target.PRODUCTO_ID = source.p_id)
	WHEN MATCHED THEN
		UPDATE SET 
			target.DISPONIBLE = target.DISPONIBLE + source.disponible,
			target.RESERVADO = target.RESERVADO + source.reservado,
			target.IMPORTACION = target.IMPORTACION + source.importacion,
			target.INKJET = target.INKJET + source.inkjet,
			target.ACONDICIONADO = target.ACONDICIONADO + source.acondicionado,
			target.REESTERILIZADO = target.REESTERILIZADO + source.reesterilizado,
			target.OBSERVADOS = target.OBSERVADOS + source.observados,
			target.VENTA_SUJETA = target.VENTA_SUJETA + source.venta_sujeta,
			target.CONSIGNACION = target.CONSIGNACION + source.consignacion,
			target.STOCK = target.STOCK + source.stock,
			target.USUARIO = 'Modificado por Servidor - ' + CAST(DATEADD(HOUR, -5, GETUTCDATE()) As VARCHAR(20))
	WHEN NOT MATCHED THEN
		INSERT (PRODUCTO_ID, IMPORTACION, INKJET, DISPONIBLE, RESERVADO, ACONDICIONADO, REESTERILIZADO, OBSERVADOS, VENTA_SUJETA, CONSIGNACION, STOCK, USUARIO)
		VALUES (source.p_id, source.importacion, source.inkjet, source.disponible, source.reservado, source.acondicionado, source.reesterilizado, source.observados, source.venta_sujeta, source.consignacion, source.stock, 'Creado por Servidor - ' + CAST(DATEADD(HOUR, -5, GETUTCDATE()) As VARCHAR(20)));
END

--DELETE FROM [STOCK_APROBADO]
--DBCC CHECKIDENT('STOCK_APROBADO', RESEED, 0)

--DBCC SQLPERF(LOGSPACE);
--BACKUP LOG SURGICORP_ERP TO DISK = 'NUL' WITH NOFORMAT, NOINIT, SKIP, NOREWIND, NOUNLOAD, STATS = 10;

SELECT * FROM [SI_BrokerDebugLog]
WHERE Error is not NULL
ORDER BY LogID desc