SELECT FCRMVH_NROGUI, FCRMVH_DESDPT, FCRMVH_DEPTRA, FCRMVH_DEPOSI, FCRMVH_SECTOR, USR_FCTTMT_DESCRIP, FCRMVH_FECALT FROM [dbo].[USR_FCRMVH] 
SELECT TOP 6000 FCRMVH_VNDDOR, * FROM [dbo].[USR_FCRMVH] 
WHERE FCRMVH_NROGUI = 'T001-50130'
--WHERE USR_FCTTMT_DESCRIP like '%UBICACION TRANSITORIA%'
ORDER BY FCRMVH_FECALT desc

-- Salidas de Guias de Remisión
SELECT * FROM [dbo].[USR_SALGUI]
WHERE SALGUI_NROGUI = 'T003-1064'
ORDER BY SALGUI_FECALT desc

-- Anulaciones de Guias de Remisión
SELECT * FROM [dbo].[USR_ANUGUI]
--WHERE ANUGUI_TIPREG = 'G'
WHERE ANUGUI_NROGUI = 'T003-1064'
ORDER BY ANUGUI_FECALT desc

--DELETE FROM [USR_ANUGUI]
--WHERE [ANUGUI_USERID] = 'JDCASTILLO'
--tablas varias
SELECT * FROM [dbo].GR_BUSQUEDA
SELECT * FROM [dbo].[FEEDBACK]
SELECT* FROM [dbo].[auth_user]
SELECT * FROM [dbo].[extended_users]
SELECT * FROM [dbo].[django_admin_log]
SELECT* FROM [dbo].[django_session]
SELECT * FROM [dbo].[USR_VALCON]
SELECT * FROM [dbo].[USR_VTRMVH]
SELECT * FROM [dbo].[SI_Empresa]
SELECT * FROM [sys].[traces]
SELECT * FROM [dbo].[HP_SCAN_PRODUCTOS]

--WHERE DESCRIPCION_PRODUCTO_HP = 'Error al buscar producto'
ORDER BY id desc
SELECT * FROM sys.messages 
WHERE severity >= 16 and language_id = 3082
ORDER BY message_id desc

-- Consultas a la cabecera de las Guias de Remision
SELECT TOP 2000 * FROM [dbo].GUIAS_REMISION 
--WHERE NUMERO_GUIA = 'T001-14559'
--WHERE CODIGO_TRANSFERENCIA is null
ORDER BY id desc
SELECT NUMERO_GUIA, COUNT(NUMERO_GUIA) AS cantidad 
FROM GUIAS_REMISION 
GROUP BY NUMERO_GUIA

-- Consultas GR_Audit
SELECT * FROM [dbo].[GR_UPDATE_AUDIT]
WHERE NUMERO_ITEM = -1
--WHERE NUMERO_GUIA = 'T003-23397'
ORDER BY id desc

-- consultas a HOJA_PICKING
SELECT * FROM [dbo].HOJA_PICKING 
WHERE SALIDA = 1
--WHERE APP_SESSION_ACTIVE is not null
ORDER BY id desc
--CREATE INDEX HP_nroGuia ON [dbo].[HOJA_PICKING] (NUMERO_GUIA);
UPDATE HOJA_PICKING
	--SET USUARIO = 'Jairo Castillo'
	SET USUARIO = 'Creado por Servidor'
WHERE NUMERO_GUIA = '0000'

-- Consultas a HP_AUDIT
SELECT * FROM [dbo].[HP_UPDATE_AUDIT] 
WHERE ESTADO_NEW = 'DELETED'
--WHERE NUMERO_GUIA = 'T003-850' --t001-46938
ORDER BY id desc

-- Consultas a Lista_Blanca
SELECT * FROM [dbo].[HP_LISTA_BLANCA]
--UPDATE HP_LISTA_BLANCA
--SET DESCRIPCION_PRODUCTO_HP = 'ROD PRE-CURV 5.5 X 40 MM'
--WHERE PRODUCTO = 'MB1RL5540'
SELECT PRODUCTO, COUNT(*) as Cantidad 
FROM dbo.HP_LISTA_BLANCA
GROUP BY producto
--HAVING COUNT(*) > 1;
SET STATISTICS TIME ON

--UPDATE GUIAS_REMISION
--	SET CODIGO_REPRESENTANTE = TRIM((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 1)),
--		OC_CLIENTE = TRIM((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 2)),
--		NRO_PROCESO = TRIM((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 3)),
--		PESO_TOTAL = CAST((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 4) as INT),
--		OBSERVACION = TRIM(IIF((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 5) = ' Anulado por Servidor ', (SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 6), (SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 5))),
--		PACIENTE = TRIM(IIF((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 5) = ' Anulado por Servidor ', (SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 7), (SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 6))),
--		FECHA_CIRUGIA = IIF((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 5) = ' Anulado por Servidor ', SUBSTRING((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 8), 2, 19), SUBSTRING((SELECT value FROM STRING_SPLIT(i.ESTADO_OLD, '|', 1) WHERE ordinal = 7), 2, 19))
--FROM (
--	SELECT * FROM [GR_UPDATE_AUDIT]
--	WHERE ESTADO_NEW = 'R103 | ---- | ---- | 1 | ID# 19161 // PED# 86443 // | JOSE CARLOS LEONARDO RODRIGUEZ ANDRADE | 2025-07-12 09:00:00.'
--	ORDER BY [GR_UPDATE_AUDIT].ID_CONCAT desc
--) as i
--WHERE GUIAS_REMISION.NUMERO_GUIA = i.NUMERO_GUIA and
--	GUIAS_REMISION.EMPRESA_ID = i.EMPRESA_ID

--INSERT INTO [dbo].[SI_Empresa](EMPRESA) VALUES('RR MEDICAL S.R.L.')
--DELETE FROM [GR_UPDATE_AUDIT] WHERE id > 463229
--DBCC CHECKIDENT('GR_UPDATE_AUDIT', RESEED, 463230)

/*UPDATE dbo.HOJA_PICKING
	SET GR_ID = i.id
	FROM GUIAS_REMISION AS i
	WHERE HOJA_PICKING.NUMERO_GUIA = i.NUMERO_GUIA AND
		HOJA_PICKING.EMPRESA_ID = i.EMPRESA_ID*/
--UPDATE dbo.HOJA_PICKING
--	SET SALIDA = 0,
--		USUARIO = 'Modificado por Servidor'
--	WHERE SALIDA is null -- and STATUS_PICKING = 'Picking Terminado'
/*UPDATE GUIAS_REMISION
SET FECHA_CIRUGIA = TRY_PARSE(CONCAT(CONVERT(date, USR_FCRMVH_FCHCIR), 
		' ', 
		STUFF(COALESCE(NULLIF(USR_FCRMVH_HORCIR, ''), '1200'), 3, 0, ':'), 
		' ', 
		IIF(USR_FCRMVH_TIPHOR = 'P', 'PM', 'AM')
	) as datetime using 'en-us'
)
FROM [USR_FCRMVH] as i
WHERE NUMERO_GUIA = i.FCRMVH_NROGUI and EMPRESA_ID = i.FCRMVH_CODEMP*/

--UPDATE GUIAS_REMISION
--	SET SALIDA = i.SALIDA
--FROM HOJA_PICKING as i
--WHERE GUIAS_REMISION.NUMERO_GUIA = i.NUMERO_GUIA and GUIAS_REMISION.EMPRESA_ID = i.EMPRESA_ID

--SELECT USER_NAME();
--EXEC sp_who2; 
--SELECT SESSION_USER usuario_BD_sesion, 
--       CURRENT_USER usuario_BD_actual, 
--       SYSTEM_USER  usuario_sistema, 
--       ORIGINAL_LOGIN() login_usado_inicialmente, 
--       SUSER_SNAME() nombe_login_asociado_a_la_sesion;

