SELECT VTRMVH_DESSED, VTRMVH_ESTDOC, * FROM [dbo].[USR_VTRMVH]
WHERE VTRMVH_NRODOC = 'F003-36939'
ORDER BY VTRMVH_FECALT desc
SELECT * FROM [dbo].[USR_VALCON]
SELECT * FROM [dbo].[USR_VTTENT]
SELECT * FROM [dbo].[USR_VTTVND]
SELECT * FROM [dbo].[USR_CUOVTA]
SELECT * FROM [dbo].[USR_IDPAPP]
SELECT * FROM [dbo].[USR_PARINT]
SELECT * FROM [dbo].[USR_PERREP]

SELECT * FROM [dbo].[USR_VTMCLH]
WHERE VTMCLH_NOMBRE like '%CLINICA%'
ORDER BY VTMCLH_NOMBRE desc

SELECT * FROM [dbo].[USR_STMLOH]
WHERE STMLOH_NSERIE = 'SERVEN02340'
ORDER BY STMLOH_FECALT desc

SELECT * FROM [dbo].[USR_VTRMVI]
WHERE VTRMVI_ARTCOD = 'SERVEN02340'

SELECT * FROM [dbo].[USR_VTRMVH]
WHERE VTRMVH_NROFOR = 429

SELECT * FROM [dbo].[QR_PRODUCTOS]
SELECT * FROM [dbo].[QR_UPDATE_AUDIT]
SELECT * FROM [dbo].[USR_PARINT]
-- Consulta a Fact busqueda
SELECT * FROM [dbo].[FACT_BUSQUEDA]
ORDER BY id desc
-- Consulta a Facturas
SELECT * FROM [dbo].[FACTURAS]
ORDER BY id desc

SELECT * FROM [dbo].[FACT_DETALLE]
WHERE NUMERO_FACTURA = 'FE0103-36939'
--WHERE NOMBRE_CLIENTE = 'AGGAYU E.I.R.L.'
ORDER BY id desc
--WHERE TIPO_VENTA <> 'T018' and 
--	VENDEDOR = 'ALARCON ORTIZ ARTURO' and 
--	(ESTADO = 'ACT' or ESTADO = 'NCA') and
--	TITULO_GRATUITO = 'N'

SELECT * FROM [REPR_COMISION_PRODUCTO]
SELECT * FROM [dbo].[REPR_COMISION]
SELECT * FROM [dbo].[REPR_COMISION_SUPERVISOR]
--ALTER TABLE [FACT_DETALLE]
--ADD RV ROWVERSION;
-- Consultas a fact_audit
SELECT * FROM [dbo].[FACT_UPDATE_AUDIT]
ORDER BY id desc
--DELETE FROM [FACT_DETALLE]
--DBCC CHECKIDENT('FACT_DETALLE', RESEED, 0)
--CREATE INDEX FACT_nro_fact ON [dbo].[FACT_DETALLE] (NUMERO_FACTURA);


--UPDATE [FACT_DETALLE]
--	SET TIPO_VENTA = i.VTRMVH_TIPVEN
--FROM [USR_VTRMVH] as i
--WHERE NUMERO_FACTURA = i.VTRMVH_NRODOC and
--	EMPRESA_ID = i.VTRMVH_CODEMP
--UPDATE FACT_DETALLE
--	SET TIPO_CLIENTE = 'PRIVADO'
--WHERE NOMBRE_CLIENTE = 'SMITH & NEPHEW INC'
