SELECT * FROM [dbo].[SI_DEPOSITO] WHERE CODIGO_DEPOSITO = 'SG-C215-C'
SELECT * FROM [dbo].[SI_TIPOALMACEN]
SELECT * FROM [dbo].[SI_SECTOR]
SELECT * FROM [dbo].[SI_KITS_prod_id]
SELECT * FROM [dbo].[SI_KITS]
SELECT * FROM [dbo].[SI_TIPOPRODUCTO]
SELECT * FROM [dbo].[USR_PARINT]
SELECT * FROM [dbo].[USR_VTTVND]
SELECT * FROM [dbo].[USR_VTTENT]
SELECT * FROM [dbo].[USR_VTMCLH]
SELECT * FROM [dbo].[SI_UPDATE_AUDIT]

-- consulta a Stock Aprobados
SELECT id, PRODUCTO_ID, DISPONIBLE, IMPORTACION, ACONDICIONADO, REESTERILIZADO, OBSERVADOS, CONSIGNACION, VENTA_SUJETA, STOCK, USUARIO 
FROM [dbo].[STOCK_APROBADO]
WHERE USUARIO is not null
-- Consultas a descripcion de stock
SELECT * FROM [dbo].[SI_DESCRIPCION]
WHERE GUIA_REMISION is not NULL

-- Consultas a la tabla de stock_inventario  --35 654
SELECT * FROM [dbo].[STOCK_INVENTARIO] as i
	LEFT JOIN SI_PRODUCTO as p ON p.id = i.PRODUCTO_ID
--WHERE OTROS is not NULL
--WHERE USUARIO like '%Servidor%'
ORDER BY USUARIO desc

--Consultas a la tabla stock de ofisis
SELECT TOP 22000 STRMVK_SECTOR, STRMVK_DEPOSI, STRMVK_TIPAMJ, STRMVK_ARTCOD, STRMVK_CANTID, * FROM [dbo].[USR_STRMVK]
WHERE STRMVK_DEPOSI like '%-CUA'
--WHERE STRMVK_TIPAMJ = ''
ORDER BY STRMVK_FECALT desc


-- Consultas a tabla Productos ofisis
SELECT * FROM [dbo].[USR_STMPDH]
--WHERE STMPDH_CODFAL is not NULL
--WHERE STMPDH_ARTCOD = 'Y-R005KC5'
ORDER BY STMPDH_FECALT desc

-- Consultas a Productos
SELECT * FROM [dbo].[SI_PRODUCTO]
WHERE CODIGO_PRODUCTO = '1001-ABR 5'

-- Consultas a grupo
SELECT * FROM [dbo].[USR_GRUNEG]
SELECT * FROM [dbo].[SI_GRUPO] 
--WHERE NOMBRE_GRUPO = 'LAMPARA'
ORDER BY NOMBRE_GRUPO

-- Consultas a linea
SELECT * FROM [dbo].[USR_LINNEG]
ORDER BY LINNEG_DESCRP
SELECT * FROM [dbo].[SI_LINEA] 
--WHERE NOMBRE_LINEA = 'LAMPARA'
ORDER BY NOMBRE_LINEA

-- Consultas a proveedor
SELECT * FROM [dbo].[USR_PVMPRH]
WHERE PVMPRH_NOMBRE = 'MINDMAZE SA'
ORDER BY PVMPRH_NOMBRE
SELECT * FROM [dbo].[SI_PROVEEDOR]
--WHERE NOMBRE_LINEA = 'LAMPARA'
ORDER BY NOMBRE_PROVEEDOR

--consultas a las familias de los productos
SELECT * FROM [dbo].[USR_FAMALT]
SELECT * FROM [dbo].[SI_FAMILIA]

--DELETE FROM [STOCK_APROBADO] WHERE id = 3091 GUIA_DIGEMID --5104  5750 1922 7026       5794 4047
--DBCC CHECKIDENT('STOCK_APROBADO', RESEED, 0)
--INSERT INTO SI_PRODUCTO (CODIGO_PRODUCTO, DESCRIPCION)
--DELETE FROM [SI_DESCRIPCION]
--DBCC CHECKIDENT('SI_DESCRIPCION', RESEED, 0)
--CREATE INDEX SI_CodProd ON [dbo].[SI_PRODUCTO] (CODIGO_PRODUCTO);    -- 208594 + 31 = 208596?

UPDATE [dbo].[SI_DESCRIPCION]
	SET DESCRIPCION_ID = NULL

--INSERT INTO SI_DESCRIPCION (CODIGO_PRODUCTO, CANTIDAD, DESCRIPCION_ID, LOTE, TIPOALMACEN_ID, DEPOSITO_ID, SECTOR_ID, TIPO_ALMACENAJE)
SELECT t.cod, t.stock, t.st_id, t.STRMVK_NSERIE, t.tp_id, t.d_id, t.s_id, t.STRMVK_TIPAMJ
	FROM (SELECT DISTINCT TOP 480000 TRIM(STRMVK_ARTCOD) as cod, p.id as p_id, SUM(STRMVK_CANTID) as stock, i.STRMVK_NSERIE, d.id as d_id, i.STRMVK_DEPOSI, s.id as s_id, i.STRMVK_SECTOR, i.STRMVK_DESSEC, tp.id as tp_id, i.STRMVK_TIPALM, st.id as st_id, i.STRMVK_TIPAMJ, dc.id FROM [USR_STRMVK] as i
		LEFT JOIN SI_PRODUCTO as p ON p.CODIGO_PRODUCTO = TRIM(i.STRMVK_ARTCOD)
		LEFT JOIN SI_DEPOSITO as d ON d.CODIGO_DEPOSITO = i.STRMVK_DEPOSI
		LEFT JOIN SI_SECTOR as s ON s.NOMBRE_SECTOR = TRIM(i.STRMVK_SECTOR)
		LEFT JOIN SI_TIPOALMACEN as tp ON tp.NOMBRE_ALMACEN = IIF(i.STRMVK_TIPALM = '', '-', i.STRMVK_TIPALM)
		LEFT JOIN STOCK_INVENTARIO as st ON st.PRODUCTO_ID = p.id
		LEFT JOIN SI_DESCRIPCION as dc ON dc.DESCRIPCION_ID = st.id and 
				dc.LOTE = i.STRMVK_NSERIE and
				dc.TIPOALMACEN_ID = tp.id and
				dc.DEPOSITO_ID = d.id and
				dc.SECTOR_ID = s.id and
				dc.TIPO_ALMACENAJE = i.STRMVK_TIPAMJ
	WHERE dc.id is NULL
	GROUP BY TRIM(STRMVK_ARTCOD), p.id, STRMVK_NSERIE, d.id, STRMVK_DEPOSI, s.id, STRMVK_SECTOR, tp.id, STRMVK_TIPALM, st.id, i.STRMVK_TIPAMJ, i.STRMVK_DESSEC, dc.id
	ORDER BY TRIM(STRMVK_ARTCOD) desc) as t


-- Insert a Stock de Inventario
--INSERT INTO STOCK_INVENTARIO (PRODUCTO_ID, ALMACENAJE, STOCK, TIPO_ALMACENAJE)
SELECT st.p_id, st.almcenaje, st.stock, st.tipo_almacenaje FROM (
	SELECT TOP 60000 p.id as p_id, STRMVK_ARTCOD as cod, p.TIPO as tipo, IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ) as tipo_almacenaje,
		(e.EMPRESA + ' | ' + IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ) + ' | ' + i.STRMVK_TIPALM) As almcenaje, SUM(STRMVK_CANTID) as stock 
	FROM [USR_STRMVK] as i
		LEFT JOIN [SI_PRODUCTO] as p ON p.CODIGO_PRODUCTO = i.STRMVK_ARTCOD and TIPO = i.STRMVK_TIPPRO
		LEFT JOIN [dbo].[SI_Empresa] As e ON e.id = i.STRMVK_CODEMP
	GROUP BY p.id, STRMVK_ARTCOD, p.TIPO, IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ), (e.EMPRESA + ' | ' + IIF(i.STRMVK_TIPAMJ = '', i.STRMVK_DEPOSI + ' - ' + i.STRMVK_SECTOR, i.STRMVK_TIPAMJ) + ' | ' + i.STRMVK_TIPALM) 
	ORDER BY STRMVK_ARTCOD, p_id desc
) as st

	-- INSERT INTO STOCK_APROBADO(PRODUCTO_ID, DISPONIBLE, IMPORTACION, ACONDICIONADO, REESTERILIZADO, OBSERVADOS, VENTA_SUJETA, CONSIGNACION, STOCK)
	SELECT TOP 60000 p.id, 
		SUM(CASE WHEN STRMVK_TIPAMJ = 'STOCK DISPONIBLE'
			or STRMVK_TIPAMJ = 'CONSUMO INTERNO'
			or STRMVK_TIPAMJ = 'DEVOLUCION EN PROCESO'
			or STRMVK_TIPAMJ = 'STOCK EN TRANSITO'
			THEN i.STRMVK_CANTID ELSE 0 END) as disponible,
		SUM(CASE WHEN STRMVK_TIPAMJ = 'PRODUCTOS OBSERVADOS POR CALIDAD'
			or STRMVK_TIPAMJ = 'IMPORTACION EN PROSO DE APROBACION'
			or STRMVK_TIPAMJ = 'INKJET'
			or STRMVK_TIPAMJ = 'COMPRA LOCAL EN PROCESO DE REVISION'
			THEN i.STRMVK_CANTID ELSE 0 END) as importacion,
		SUM(CASE WHEN STRMVK_TIPAMJ = 'PRODUCTOS EN ACONDICIONADO' THEN i.STRMVK_CANTID ELSE 0 END) as acondicionado,
		SUM(CASE WHEN STRMVK_TIPAMJ = 'PRODUCTO REESTERILIZADO' THEN i.STRMVK_CANTID ELSE 0 END) as reesterilizado,
		SUM(CASE WHEN STRMVK_SECTOR = '7-B.1' 
			or STRMVK_SECTOR = '7-B.2'
			or STRMVK_SECTOR = '7-B.3'
			or STRMVK_SECTOR = 'PRI-R75.A.1'
			THEN i.STRMVK_CANTID ELSE 0 END) as observados,
		SUM(CASE WHEN STRMVK_TIPAMJ = 'VTA. SUJET. A CONF(MER)/BIENES DE USO' THEN i.STRMVK_CANTID ELSE 0 END) as venta_sujeta,
		SUM(CASE WHEN STRMVK_TIPAMJ = 'CONSIGNACION' THEN i.STRMVK_CANTID ELSE 0 END) as consignacion,
		SUM(CASE WHEN STRMVK_TIPAMJ = 'STOCK DISPONIBLE' 
			or STRMVK_TIPAMJ = 'PRODUCTOS OBSERVADOS POR CALIDAD'
			or STRMVK_TIPAMJ = 'IMPORTACION EN PROSO DE APROBACION'
			or STRMVK_TIPAMJ = 'INKJET'
			or STRMVK_TIPAMJ = 'COMPRA LOCAL EN PROCESO DE REVISION'
			or STRMVK_TIPAMJ = 'CONSUMO INTERNO'
			or STRMVK_TIPAMJ = 'DEVOLUCION EN PROCESO'
			or STRMVK_TIPAMJ = 'STOCK EN TRANSITO'
			or STRMVK_TIPAMJ = 'PRODUCTOS EN ACONDICIONADO'
			or STRMVK_TIPAMJ = 'PRODUCTO REESTERILIZADO'
			or STRMVK_TIPAMJ = 'VTA. SUJET. A CONF(MER)/BIENES DE USO'
			or STRMVK_TIPAMJ = 'CONSIGNACION' 
			THEN i.STRMVK_CANTID ELSE 0 END) as stock
	FROM [USR_STRMVK] as i
		LEFT JOIN [dbo].[SI_Empresa] As e ON e.id = i.STRMVK_CODEMP
		OUTER APPLY (
					SELECT TOP 1 *
					FROM [SI_PRODUCTO] as p
					WHERE p.CODIGO_PRODUCTO = i.STRMVK_ARTCOD
						and TIPO = i.STRMVK_TIPPRO
					ORDER BY p.ID -- Aquí decides cuál de las dos cuentas priorizar	IMPORTACION EN PROSO DE APROBACION
				) as p
	GROUP BY STRMVK_ARTCOD, p.id
	ORDER BY STRMVK_ARTCOD asc