--DELETE FROM [dbo].[PEND_ITEMS]
--DBCC CHECKIDENT('PEND_ITEMS', RESEED, 0)
SELECT * FROM [dbo].[auth_user] --user client123

SELECT * FROM SURGICORP_POWERAPPS.[dbo].[GUIPEN_PWRAPP] ORDER BY NUMERO_GUIA DESC --9 041
--SELECT * FROM SURGICORP_POWERAPPS.[dbo].[PEND_GUIAS] ORDER BY NUMERO_GUIA DESC	--1 437		--T001-7575
--SELECT DISTINCT(NUMERO_GUIA), EMPRESA FROM SURGICORP_POWERAPPS.[dbo].[GUIPEN_PWRAPP] --ORDER BY NUMERO_GUIA DESC --1 436
SELECT * FROM SURGICORP_POWERAPPS.[dbo].[PEND_ITEMS] /*WHERE NUMERO_GUIA='T001-7575'*/ ORDER BY NUMERO_GUIA DESC	--9 041
SELECT * FROM SURGICORP_POWERAPPS.[dbo].[PEND_UPDATE_AUDIT] ORDER BY id DESC