SELECT VTRMVH_DESSED, VTRMVH_ESTDOC, * FROM [dbo].[USR_VTRMVH]
WHERE VTRMVH_NRODOC = 'F001-8149'
ORDER BY VTRMVH_FECALT desc

SELECT * FROM [dbo].[USR_STMLOH]
WHERE STMLOH_NSERIE = '5181884S.'
ORDER BY STMLOH_FECALT desc
SELECT * FROM [dbo].[QR_PRODUCTOS]
SELECT * FROM [dbo].[QR_UPDATE_AUDIT]
SELECT * FROM [dbo].[USR_PARINT]
-- Consulta a Fact busqueda
SELECT * FROM [dbo].[FACT_BUSQUEDA]
ORDER BY id desc
-- Consulta a Facturas
SELECT * FROM [dbo].[FACT_DETALLE]
--WHERE NUMERO_FACTURA = 'F003-14384'
ORDER BY id desc
--ALTER TABLE [FACT_DETALLE]
--ADD RV ROWVERSION;
-- Consultas a fact_audit
SELECT * FROM [dbo].[FACT_UPDATE_AUDIT]
ORDER BY id desc
--DELETE FROM [FACT_DETALLE]
--DBCC CHECKIDENT('FACT_DETALLE', RESEED, 0)