SELECT  * FROM [dbo].HP_PROVEEDOR
--WHERE NUMERO_GUIA='T001-7451' --and
--where (OC_CLIENTE='') --and 450130 448954
ORDER BY id desc
--FECHA_GUIA >= DATEADD(DAY,-1,CURRENT_TIMESTAMP)
--FECHA_GUIA >= Cast(CURRENT_TIMESTAMP as date)
--DELETE FROM GR_BUSQUEDA
--DBCC CHECKIDENT('GR_BUSQUEDA', RESEED, 0)
SELECT TOP 4500 * FROM [dbo].DOCGUI_PWRAPP
--WHERE NRO_PROCESO<>''  
ORDER BY ID DESC 
--SELECT TOP 1500 * FROM [dbo].[GUIAS_REMISION] ORDER BY id DESC 
--SELECT TOP 2500 * FROM [dbo].[GUIAS_REMISION_OC] ORDER BY id DESC
--SELECT * FROM [dbo].[GR_DESCRIPCION] WHERE NUMERO_GUIA='T003-22650' ORDER BY id DESC --571 272
--SELECT TOP 3500 * FROM [dbo].[GR_DESCRIPCION_OC] ORDER BY id DESC --6197
--SELECT * FROM [dbo].[DOCGUI_PWRAPP] WHERE /*(OC_CLIENTE='' or OC_CLIENTE  is null) and*/ EMPRESA='03' ORDER BY FECHA_GUIA DESC --580 120
--SELECT TOP 1500 * FROM [dbo].GR_BUSQUEDA WHERE NUMERO_GUIA='T001-39209' ORDER BY id DESC 
--DELETE FROM [GR_DESCRIPCION_OC]
--DBCC CHECKIDENT('GR_DESCRIPCION_OC', RESEED, 0)
SELECT TOP 2000 * FROM [dbo].[HOJA_PICKING]
WHERE NUMERO_GUIA = 'T001-39290'
ORDER BY id desc
/*UPDATE HOJA_PICKING
SET STATUS_PICKING = 'Picking En Proceso'
WHERE NUMERO_GUIA = 'T001-37164'*/
SELECT TOP 1000 id,NUMERO_GUIA,OC_CLIENTE,LIMA_PROVINCIA FROM [dbo].[HOJA_PICKING]
--WHERE LIMA_PROVINCIA = 2 
ORDER BY id desc
--sp_get_distributor
--SELECT TOP 1000 * FROM [dbo].[DOCGUI_PWRAPP] WHERE NUMERO_GUIA='T003-18145'
/*UPDATE GR_BUSQUEDA
SET EMPRESA_ID = i.EMPRESA_ID
FROM [GUIAS_REMISION_OC] AS i
WHERE GR_BUSQUEDA.NUMERO_GUIA = i.NUMERO_GUIA and GR_BUSQUEDA.ID_APP = i.ID_APP
--FROM (SELECT DISTINCT(NUMERO_GUIA), EMPRESA, DEPOSITO FROM [DOCGUI_PWRAPP]) AS i
WHERE [HOJA_PICKING].NUMERO_GUIA = i.NUMERO_GUIA AND [HOJA_PICKING].EMPRESA_ID = i.EMPRESA*/
--SELECT COUNT(*) FROM (SELECT DISTINCT(NUMERO_GUIA), EMPRESA, OC_CLIENTE FROM DOCGUI_PWRAPP) AS i WHERE i.OC_CLIENTE !='' --50485 --2059
--SELECT COUNT(*) FROM [dbo].[GUIAS_REMISION]  --51802
--SELECT COUNT(*) FROM [dbo].[GUIAS_REMISION_OC]  --2060
--CREATE INDEX SI_prod ON [dbo].[STOCKS_INVENTARIO] (PRODUCTO);
SELECT * FROM [dbo].[django_content_type]
--UPDATE [GR_DESCRIPCION_OC]
--SET KITS_ITEM = i.KITS_ITEM
--FROM [DOCGUI_PWRAPP] AS i
--WHERE [GR_DESCRIPCION_OC].NUMERO_GUIA = i.NUMERO_GUIA AND [GR_DESCRIPCION_OC].EMPRESA_ID = i.EMPRESA and [GR_DESCRIPCION_OC].NUMERO_ITEM = i.NRO_ITEM
SELECT TOP 2000 * FROM [dbo].[HP_UPDATE_AUDIT]
WHERE NUMERO_GUIA ='T001-39054'
ORDER BY id desc
SELECT TOP 2000 * FROM [dbo].[GR_UPDATE_AUDIT]
ORDER BY id desc