SELECT * FROM [dbo].[SI_DEPOSITO] WHERE CODIGO_DEPOSITO = 'SG-C215-C'
SELECT * FROM [dbo].[SI_TIPOALMACEN]
SELECT * FROM [dbo].[SI_LINEA]
SELECT * FROM [dbo].[SI_SECTOR]
SELECT * FROM [dbo].[SI_KITS_prod_id]
SELECT * FROM [dbo].[SI_KITS]
SELECT * FROM [dbo].[SI_TIPOPRODUCTO]
SELECT * FROM [dbo].[USR_PARINT]

-- Consultas a descripcion de stock
SELECT * FROM [dbo].[SI_DESCRIPCION]

-- Consultas a la tabla de stock_inventario
SELECT * FROM [dbo].[STOCK_INVENTARIO]
WHERE USUARIO = 'Modificado por [ProcessStockUpdates]'

--Consultas a la tabla stock de ofisis
SELECT TOP 80 * FROM [dbo].[USR_STRMVK]
--WHERE STRMVK_STOCKS > 0
--WHERE STRMVK_ARTCOD = 'PCAN30-410'
ORDER BY STRMVK_FECALT desc
--INSERT INTO [SI_SECTOR]
SELECT DISTINCT STRMVK_TIPAMJ FROM [USR_STRMVK] as i
	LEFT JOIN [SI_SECTOR] as d ON d.NOMBRE_SECTOR = i.STRMVK_SECTOR
WHERE d.id is NULL

-- Consultas a tabla Productos ofisis
SELECT * FROM [dbo].[USR_STMPDH]
--WHERE STMPDH_ARTCOD = '2.5A 250V'
ORDER BY STMPDH_FECALT

-- Consultas a tabla intermedia producto_tipoproducto
SELECT * FROM [dbo].[SI_PRODUCTO_tp_id]
	LEFT JOIN [SI_PRODUCTO] as p ON p.id = si_producto_id
--WHERE CODIGO_PRODUCTO = '15-1133/03E'
ORDER BY si_producto_id

-- Consultas a SI Productos
SELECT DISTINCT CODIGO_PRODUCTO, DESCRIPCION FROM [dbo].[SI_PRODUCTO]
SELECT * FROM [dbo].[SI_PRODUCTO]
WHERE CODIGO_PRODUCTO = '1001-ABR 5'

-- Consultas a grupo
SELECT * FROM [dbo].[SI_GRUPO] 
--WHERE NOMBRE_GRUPO = 'LAMPARA'
ORDER BY NOMBRE_GRUPO

-- Consultas a linea
SELECT * FROM [dbo].[SI_LINEA] 
--WHERE NOMBRE_LINEA = 'LAMPARA'
ORDER BY NOMBRE_LINEA

-- Consultas a proveedor
SELECT * FROM [dbo].[SI_PROVEEDOR]
--WHERE NOMBRE_LINEA = 'LAMPARA'
ORDER BY NOMBRE_PROVEEDOR

--DELETE FROM [STOCK_INVENTARIO] WHERE id = 3091 GUIA_DIGEMID --5104  5750 1922 7026       5794 4047
--DBCC CHECKIDENT('STOCK_INVENTARIO', RESEED, 0)
--INSERT INTO SI_PRODUCTO (CODIGO_PRODUCTO, DESCRIPCION)
--DELETE FROM [SI_DESCRIPCION]
--DBCC CHECKIDENT('SI_DESCRIPCION', RESEED, 0)
--CREATE INDEX SI_CodProd ON [dbo].[SI_PRODUCTO] (CODIGO_PRODUCTO);    -- 208594 + 31 = 208596?

--INSERT INTO SI_DESCRIPCION (CODIGO_PRODUCTO, CANTIDAD, DESCRIPCION_ID, LOTE, TIPOALMACEN_ID, DEPOSITO_ID, SECTOR_ID, TIPO_ALMACENAJE)
SELECT t.cod, t.stock, t.st_id, t.STRMVK_NSERIE, t.tp_id, t.d_id, t.s_id, t.STRMVK_TIPAMJ
	FROM (SELECT DISTINCT TOP 480000 TRIM(STRMVK_ARTCOD) as cod, p.id as p_id, SUM(STRMVK_CANTID) as stock, i.STRMVK_NSERIE, d.id as d_id, i.STRMVK_DEPOSI, s.id as s_id, i.STRMVK_SECTOR, i.STRMVK_DESSEC, tp.id as tp_id, i.STRMVK_TIPALM, st.id as st_id, i.STRMVK_TIPAMJ, dc.id FROM [USR_STRMVK] as i
		LEFT JOIN SI_PRODUCTO as p ON p.CODIGO_PRODUCTO = TRIM(i.STRMVK_ARTCOD)
		LEFT JOIN SI_DEPOSITO as d ON d.CODIGO_DEPOSITO = i.STRMVK_DEPOSI
		LEFT JOIN SI_SECTOR as s ON s.NOMBRE_SECTOR = TRIM(i.STRMVK_SECTOR)
		LEFT JOIN SI_TIPOALMACEN as tp ON tp.NOMBRE_ALMACEN = IIF(i.STRMVK_TIPALM = '', '-', i.STRMVK_TIPALM)
		LEFT JOIN STOCK_INVENTARIO as st ON st.PRODUCTO_ID = p.id
		LEFT JOIN SI_DESCRIPCION as dc ON dc.DESCRIPCION_ID = st.id and 
				dc.LOTE = i.STRMVK_NSERIE and
				dc.TIPOALMACEN_ID = tp.id and
				dc.DEPOSITO_ID = d.id and
				dc.SECTOR_ID = s.id and
				dc.TIPO_ALMACENAJE = i.STRMVK_TIPAMJ
	WHERE dc.id is NULL
	GROUP BY TRIM(STRMVK_ARTCOD), p.id, STRMVK_NSERIE, d.id, STRMVK_DEPOSI, s.id, STRMVK_SECTOR, tp.id, STRMVK_TIPALM, st.id, i.STRMVK_TIPAMJ, i.STRMVK_DESSEC, dc.id
	ORDER BY TRIM(STRMVK_ARTCOD) desc) as t

--INSERT INTO STOCK_INVENTARIO (PRODUCTO_ID, STOCK)
SELECT t.p_id, t.stock FROM (
SELECT DISTINCT TOP 9000 TRIM(STRMVK_ARTCOD) as cod, p.id as p_id, SUM(STRMVK_CANTID) as stock FROM [USR_STRMVK] as i
	LEFT JOIN [SI_PRODUCTO] as p ON p.CODIGO_PRODUCTO = TRIM(i.STRMVK_ARTCOD)
GROUP BY TRIM(STRMVK_ARTCOD), p.id
ORDER BY TRIM(STRMVK_ARTCOD) desc) as t


