SELECT * FROM [dbo].[USR_VTRMVH]
SELECT * FROM [dbo].[USR_STMLOH]
WHERE STMLOH_NSERIE = '5181884S.'
ORDER BY STMLOH_FECALT desc
SELECT * FROM [dbo].[QR_PRODUCTOS]
SELECT * FROM [dbo].[QR_UPDATE_AUDIT]
SELECT * FROM [dbo].[USR_PARINT]
SELECT * FROM [dbo].[FACT_DETALLE]
ORDER BY id desc
SELECT * FROM [dbo].[FACT_UPDATE_AUDIT]
ORDER BY id desc
--DELETE FROM [FACT_DETALLE]
--DBCC CHECKIDENT('FACT_DETALLE', RESEED, 0)