SELECT * FROM [dbo].[USR_STMPDH]
--WHERE STMPDH_LINEAD = 'EQUIPOS MÉDICOS' and STMPDH_NOMPRO like 'HUMECA%'
WHERE STMPDH_ARTCOD = '1749'
ORDER BY STMPDH_FECALT desc


--Consultas a la tabla stock de ofisis
SELECT /*TOP 22000*/ STRMVK_SECTOR, STRMVK_DEPOSI, STRMVK_TIPAMJ, STRMVK_TIPPRO, STRMVK_ARTCOD, STRMVK_NSERIE, STRMVK_CANTID, * FROM [dbo].[USR_STRMVK]
--WHERE STRMVK_DEPOSI like '%-CUA'
WHERE STRMVK_ARTCOD = 'A4-ABDO1-K'
	and STRMVK_TIPAMJ = 'STOCK DISPONIBLE'
	--and STRMVK_DESDEP = 'CLINICA LA MERCED S.A.C.'
	--and STRMVK_NSERIE = 'X11072'
	--and STRMVK_DEPOSI = 'RRM-C09-VS' 
	--and STRMVK_DEPOSI <> 'RRM-C824-VS'
	--WHERE  STRMVK_TIPALM = ''
ORDER BY STRMVK_FECALT desc

SELECT STRMVK_NSERIE, STRMVK_TIPPRO, STRMVK_ARTCOD,  STRMVK_TIPAMJ, STRMVK_TIPALM, SUM(STRMVK_CANTID) As Cant FROM [dbo].[USR_STRMVK]
WHERE STRMVK_ARTCOD = 'A4-ABDO1-K'
	--and STRMVK_NSERIE = '12/2022'
	--and STRMVK_TIPAMJ = 'VTA. SUJET. A CONF(MER)/BIENES DE USO'
	--and STRMVK_DEPOSI <> 'RRM-C09-VS' 
	--and STRMVK_DEPOSI <> 'RRM-C824-VS'
	--and STRMVK_DEPOSI <> 'RRM-C97-VS'
GROUP BY STRMVK_NSERIE, STRMVK_TIPPRO, STRMVK_ARTCOD,  STRMVK_TIPAMJ, STRMVK_TIPALM
HAVING SUM(STRMVK_CANTID) != 0


SELECT TIPO_ALMACENAJE FROM STOCK_INVENTARIO
GROUP BY TIPO_ALMACENAJE
