SELECT EQUVAC_CODEMP, EQUVAC_MODFOR, EQUVAC_CODFOR, EQUVAC_NROFOR, EQUVAC_NROITM, EQUVAC_NIVEXP, EQUVAC_DEPOSI, 
	EQUVAC_SECTOR, EQUVAC_NSERIE, EQUVAC_NOTROS, EQUVAC_FCHMOV, EQUVAC_TIPPRO, EQUVAC_ARTCOD, EQUVAC_DESART, 
	EQUVAC_CANTID, EQUVAC_NROCTA, EQUVAC_NOMCLI, EQUVAC_NOMPAC, EQUVAC_VNDDOR, EQUVAC_DESVND, EQUVAC_FECALT
FROM dbo.USR_EQUVAC
WHERE EQUVAC_DEPOSI = 'SG-APR'
ORDER BY EQUVAC_FECALT desc
