--INSERT INTO SI_Productos (PRODUCTO, DESCRIPCION_PRODUCTO, grupo_id_id)
SELECT TOP 1500 * FROM SURGICORP_POWERAPPS.[dbo].[STOCKS_PWRAPP] --AS S
--INNER JOIN [dbo].[SI_GRUPO] AS G ON id = 253  --778 773 vs 782 335
WHERE PRODUCTO = 'MB1MSS640' and STOCK > 0
SELECT DESCRIPCION_PRODUCTO, SUM(STOCK) AS Total_stock FROM SURGICORP_POWERAPPS.[dbo].[STOCKS_INVENTARIO] 
WHERE DESCRIPCION_PRODUCTO LIKE '%MEPILEX%' and STOCK > 0
GROUP BY DESCRIPCION_PRODUCTO
ORDER BY DESCRIPCION_PRODUCTO
--order by id desc
--order by STOCK --desc;
--DATEADD(DAY, -1,CURRENT_TIMESTAMP) 31,036 31,552   230331AL11 230908BL3 230925AL4 230922BL1
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_Productos ORDER BY id desc
--SELECT DISTINCT(PRODUCTO), DESCRIPCION_PRODUCTO, GRUPO FROM [dbo].[STOCKS_PWRAPP]
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_Grupo ORDER BY id desc
--SELECT DISTINCT(ST.GRUPO), L.id FROM [dbo].[STOCKS_PWRAPP] AS ST INNER JOIN dbo.SI_Linea AS L ON L.LINEA = ST.LINEA ORDER BY GRUPO
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_Linea ORDER BY id desc
--SELECT DISTINCT(LINEA) FROM [dbo].[STOCKS_PWRAPP]
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_Sector ORDER BY SECTOR --desc
--SELECT DISTINCT(SECTOR) FROM [dbo].[STOCKS_PWRAPP]
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_Depositos ORDER BY id desc
--SELECT DISTINCT(ST.DEPOSITO), ST.DESCRIPCION_DEPOSITO, E.id FROM [dbo].[STOCKS_PWRAPP] AS ST INNER JOIN SI_Empresa AS E ON E.EMPRESA = ST.EMPRESA ORDER BY DEPOSITO
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_Empresa ORDER BY id
--SELECT DISTINCT(EMPRESA) FROM [dbo].[STOCKS_PWRAPP]
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_TipoAlmacen ORDER BY id
--SELECT DISTINCT(TIPO_ALMACEN) FROM [dbo].[STOCKS_PWRAPP]
SELECT * FROM SURGICORP_POWERAPPS.dbo.SI_TipoProductos ORDER BY id
--SELECT DISTINCT(TIPO_PRODUCTO) FROM [dbo].[STOCKS_PWRAPP]
SELECT * FROM SURGICORP_POWERAPPS.[dbo].[HP_PROVEEDOR] ORDER BY id desc
SELECT TOP 1500 * FROM SURGICORP_POWERAPPS.[dbo].[SI_UPDATE_AUDIT] 
WHERE PRODUCTO = 'MB1MSS640'
ORDER BY id desc
SELECT TOP 2500 * FROM SURGICORP_POWERAPPS.[dbo].[STOCKS_INVENTARIO] 
--WHERE id > 786267 
ORDER BY STOCK desc
/*INSERT INTO [dbo].[STOCKS_INVENTARIO] ([prod_id_id], [dep_id_id], [sector_id_id], [tipoAlm_id_id], 
[tipoProd_id_id],[STOCK], [LOTE], [FECHA_VIGENCIA_LOTE], [TIPO_ALMACENAJE], [REGISTRO_SANITARIO], 
[FECHA_VIGENCIA_REGSAN], [DESCRIPCION_DEPOSITO])
SELECT P.[id], D.[id], S.[id], TA.[id], TP.[id], ST.[STOCK], ST.[LOTE], ST.[FECHA_VIGENCIA_LOTE], 
ST.[TIPO_ALMACENAJE], ST.[REGISTRO_SANITARIO], ST.[FECHA_VIGENCIA_REGSAN], ST.[DESCRIPCION_DEPOSITO]
FROM [dbo].[STOCKS_PWRAPP] AS ST 
INNER JOIN [dbo].[SI_Depositos] AS D ON ST.DEPOSITO = D.[DEPOSITO]
INNER JOIN [dbo].[SI_Productos] AS P ON ST.PRODUCTO = P.[PRODUCTO] 
AND ST.GRUPO = P.GRUPO
--AND ST.LINEA = (SELECT LINEA FROM [dbo].[SI_Linea] WHERE id = (SELECT linea_id_id FROM [dbo].[SI_Grupo] WHERE GRUPO = (SELECT GRUPO FROM SI_Productos WHERE PRODUCTO = ST.PRODUCTO)))
INNER JOIN [dbo].[SI_Sector] AS S ON ST.SECTOR = S.[SECTOR]
INNER JOIN [dbo].[SI_TipoAlmacen] AS TA ON ST.TIPO_ALMACEN = TA.[TIPO_ALMACEN]
INNER JOIN [dbo].[SI_TipoProductos] AS TP ON ST.TIPO_PRODUCTO = TP.[TIPO_PRODUCTO]
--WHERE STOCK>0 
order by ST.[STOCK] desc*/ 
--SELECT * FROM [dbo].[auth_user]
--DBCC CHECKIDENT('SI_UPDATE_AUDIT', RESEED, 0)
--DELETE FROM [dbo].[SI_UPDATE_AUDIT]
--DROP TRIGGER SI_TriggerUpdate ON ALL SERVER
